[book]
authors = ["Emirhan Tala", "Ulaş Can Demirbağ"]
language = "en"
src = "src"
title = "Deloxide User Manual"

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/Emivvvvv/deloxide"
site-url = "/deloxide/"
